### ISSUE TITLE
コンフィグのキー名変える

### ISSUE THREAD

**Issue by wawakakakyakya** [wawakakakyakya/dns_updater#10]
```yaml
- env: mydns
  timeout: 30
  mydns:
    username: username
    password: password
```
```yaml
- env: mydns
  timeout: 30
  values:
    username: username
    password: password
```
